name: CI

#será executado toda vez que alguem fizer push ou criar um pull_request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
  execution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Execute code
      run: |
        python src/main.py
